// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWbNF_YpTod9R8gPfF7KPMnRPJcd709vw',
    appId: '1:900938219262:web:187531dc3af6e029c7afaf',
    messagingSenderId: '900938219262',
    projectId: 'translatorapp-aac3c',
    authDomain: 'translatorapp-aac3c.firebaseapp.com',
    storageBucket: 'translatorapp-aac3c.appspot.com',
    measurementId: 'G-1PJFY4EQS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOEEjBchPhimMQihXKX-ZXu5yW3UUiyOE',
    appId: '1:900938219262:android:7ed5490c11056cc2c7afaf',
    messagingSenderId: '900938219262',
    projectId: 'translatorapp-aac3c',
    storageBucket: 'translatorapp-aac3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QnarB7bP7MBYQRc42s4hwSJXOY7396A',
    appId: '1:900938219262:ios:3be4ab0240ce30ccc7afaf',
    messagingSenderId: '900938219262',
    projectId: 'translatorapp-aac3c',
    storageBucket: 'translatorapp-aac3c.appspot.com',
    iosBundleId: 'com.example.translatorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4QnarB7bP7MBYQRc42s4hwSJXOY7396A',
    appId: '1:900938219262:ios:757c258b0c062350c7afaf',
    messagingSenderId: '900938219262',
    projectId: 'translatorapp-aac3c',
    storageBucket: 'translatorapp-aac3c.appspot.com',
    iosBundleId: 'com.example.translatorapp.RunnerTests',
  );
}
